### PR TITLE
Add support for fixed stack slots

### LINKED ISSUE #12: Support explicit stack slots
This is useful for functions which take many arguments and return many values, some of which are in registers while the rest are in ABI-specified stack slots.

I think the best way to add support for fixed stack slots is to add an extra bit to `PReg` to add 32 integer stack slots and 32 float stack slots.

Implementation-wise, a fixed stack slot is very similar to `Operand::Fixed`:
- The same fixups are required in case of multiple `Fixed` uses of the same vreg.
- Live ranges assigned to a fixed stack slot need to tracked just like a `PReg`.
- Allocation into fixed stack slots must be done in `process_bundle`: we may need to split a bundle in case of conflicts or evict another conflicting bundle.
- Requirement computation only needs minor changes to merge `Requirement::Stack` with `Requirement::Fixed(preg)` when `preg` refers to a fixed stack slot.
- A spill weight of 2000 still makes sense for fixed stack slots: we need expensive moves if we don't get the stack slot that we want.

### PR DESCRIPTION
**Pull request by Amanieu**
This PR adds the ability to mark a `PReg` as being a fixed stack slot through `MachineEnv`. This means that:
- The `PReg` can be specified using `OperandConstraint::FixedReg`.
- This `PReg` can be selected for `OperandConstraint::Stack`, but not `OperandConstraint::Reg`. It also cannot be used with `OperandConstraint::Reuse`, which only works with a `OperandConstraint::Reg`.
- Fixed stack slot allocations are returns as an `Allocation::reg`, just like a normal fixed stack slot.
- A `VReg` marked as `requires_refs_on_stack` can be placed into a fixed stack slot instead of a spillslot.

I'm not too happy about the API (`PReg` stands for "physical register", which feels wrong here) but it was the cleanest way to integrate this into the rest of the codebase.

Fixes #12

### CODE REVIEW

File: src/ion/liveranges.rs [hunk 1]
```diff
@@ -1159,66 +1180,108 @@ impl<'a, F: Function> Env<'a, F> {
...
+                            // Reg/FixedReg constraints. FixedReg is
+                            // incompatible if there already is a different
+                            // FixedReg constraint.
+                            if !(requires_reg && self.pregs[preg.index()].is_stack)
+                                && *first_preg.get_or_insert(preg) == preg
+                            {
+                                continue;
+                            }
+
+                            log::trace!(" -> duplicate; switching to constraint Reg");
```
Comment (cfallin) [inline src/ion/liveranges.rs:1264]: I think it might be pre-existing but the trace message should say we're switching to `Any`, no?

File: src/ion/liveranges.rs [hunk 2]
```diff
@@ -1159,66 +1180,108 @@ impl<'a, F: Function> Env<'a, F> {
...
+                                "at pos {:?}, vreg {:?} has fixed constraint to preg {:?}",
+                                u.pos,
+                                vreg_idx,
+                                preg_idx
+                            );
+
+                            // FixedStack is incompatible if there are any
+                            // Reg/FixedReg constraints. FixedReg is
+                            // incompatible if there already is a different
+                            // FixedReg constraint.
```
Comment (cfallin) [inline src/ion/liveranges.rs:1257]: A little more to this comment would help understanding I think: "If either condition is true, we edit the constraint below; otherwise, we can skip this edit."

File: src/ion/requirement.rs [hunk 3]
```diff
@@ -31,39 +32,53 @@ impl Requirement {
...
             OperandConstraint::Reg | OperandConstraint::Reuse(_) => Requirement::Register,
             OperandConstraint::Stack => Requirement::Stack,
             _ => Requirement::Any,
         }
     }
-}
 
-impl<'a, F: Function> Env<'a, F> {
-    pub fn compute_requirement(&self, bundle: LiveBundleIndex) -> Requirement {
+    pub fn compute_requirement(&self, bundle: LiveBundleIndex) -> (Requirement, ProgPoint) {
```
Comment (cfallin) [inline src/ion/requirement.rs:65]: A doc-comment describing the return value here would be useful. Actually, a struct might be nice: something like

```
struct RequirementResult {
    pub req: Requirement,
    pub needs_split: Option<ProgPoint>,
}
```

for readability maybe?

Comment (cfallin) [reply src/ion/requirement.rs:65]: (Good idea to return the splitpoint eagerly rather than re-scanning to find it later, by the way -- every little efficiency improvement counts!)

File: src/ion/requirement.rs [hunk 4]
```diff
@@ -31,39 +32,53 @@ impl Requirement {
...
                 req = req.merge(r);
                 log::trace!("     -> req {:?}", req);
+                if req == Requirement::Conflict {
+                    return (req, u.pos);
+                }
             }
         }
         log::trace!(" -> final: {:?}", req);
-        req
+        (req, ranges.first().unwrap().range.from)
```
Comment (cfallin) [inline src/ion/requirement.rs:82]: Perhaps I slightly misunderstand the purpose of the `ProgPoint`, given this -- in this case we don't need a split, so I guess we can return `None` (if `Option` as I suggested above)?

File: src/ion/liveranges.rs [hunk 5]
```diff
@@ -1159,66 +1180,108 @@ impl<'a, F: Function> Env<'a, F> {
...
-                    usize,
-                )>| {
-                    if last_point.is_some() && Some(pos) != last_point {
-                        seen_fixed_for_vreg.clear();
-                        first_preg.clear();
+
+                // Find groups of uses that occur in at the same program point.
+                for uses in self.ranges[range.index()]
+                    .uses
+                    .group_by_mut_(|a, b| a.pos == b.pos)
```
Comment (cfallin) [inline src/ion/liveranges.rs:1187]: This is a nice API but it's unfortunate that it's not yet stable, and that we have to copy part of stdlib into `util.rs` to get it; I'd prefer not to duplicate like that, and to add a few hundred lines of code to save just a few here. Until we have stabilized `group_by_mut`, could we just do the scan manually here?

**Review by cfallin — COMMENTED** [review]
Thanks so much for this contribution!

I have a few minor comments, but this looks great overall, very carefully done.

File: src/ion/liveranges.rs (hunk 5 above)
Comment (Amanieu) [reply src/ion/liveranges.rs:1187]: I actually tried to do the scan manually at first and the result was an unreadable mess. Hiding the logic to group entries by `ProgPoint` makes the loop *much* more readable.

I can shrink down the code in `util.rs` to only contain the parts that we actually needs (e.g. we don't use `group_by`, only `group_by_mut`). Alternatively, the itertools crate also provides a version of `group_by` (with slightly different arguments).

Comment (cfallin) [reply src/ion/liveranges.rs:1187]: Ah, I think using `itertools` is reasonable for now, then; it's a pretty small dep and if it improves readability here, then all the better. (IIRC there are similar scan-and-find-groups patterns in e.g. move resolution; maybe we can clean those up too later, but that's obviously outside the scope of this PR!)

**Comment by Amanieu** [comment]
I've applied the feedback from the review and also done a bit more cleanup on the API for interacting with requirements (it uses `Result::Err` to report a conflict, which is more Rust-y).

**Review by cfallin — APPROVED** [review]
Looks great, thanks!
