### PR TITLE
Fix fuzzbug related to bundle priority ordering.

### LINKED ISSUE #19: Fuzzer test failure
While running the fuzzer overnight, I got this failure (reproduces on the main branch):
```
thread '<unnamed>' panicked at 'Could not allocate minimal bundle, but the allocation problem should be possible to solve', /home/amanieu/code/regalloc2/src/ion/process.rs:1018:17
```

The fuzz testcase which reproduces this issue is [here](https://gist.github.com/Amanieu/8dbdf1b2f765870b6f86b809a2b4a5a3) (base64-encoded, use `base64 -d` to decode).

The input program is:
```
TestCase {
    func: {
      REF: v0
      REF: v2
      REF: v3
      REF: v4
      REF: v5
      REF: v6
      REF: v7
      REF: v8
      REF: v10
      REF: v14
      REF: v15
      REF: v49
      REF: v50
      REF: v51
      REF: v57
      REF: v58
      REF: v82
      REF: v83
      REF: v84
      REF: v85
      REF: v86
      REF: v87
      REF: v88
      REF: v89
      REF: v90
      REF: v91
      REF: v92
      REF: v95
      REF: v96
      REF: v97
      REF: v98
      REF: v99
      REF: v100
      REF: v101
      REF: v102
      REF: v105
      REF: v106
      REF: v107
      REF: v108
      REF: v109
      REF: v110
      REF: v111
      REF: v112
      REF: v113
      REF: v114
      REF: v115
      REF: v116
      REF: v117
      REF: v118
      REF: v119
      REF: v120
      REF: v121
      REF: v122
      REF: v123
      REF: v124
      REF: v126
      REF: v127
      REF: v128
      REF: v129
      REF: v130
      REF: v131
      REF: v132
      REF: v133
      REF: v134
      REF: v135
      REF: v136
      REF: v137
      REF: v138
      REF: v139
      REF: v140
      REF: v141
      REF: v142
      REF: v143
      REF: v144
      REF: v145
      REF: v146
      REF: v147
      REF: v153
      REF: v154
      REF: v155
      REF: v156
      REF: v157
      REF: v158
      REF: v159
      REF: v160
      REF: v170
      REF: v187
      REF: v188
      REF: v189
      REF: v190
      REF: v191
      REF: v209
      REF: v210
      REF: v211
      REF: v212
      REF: v213
      REF: v214
      REF: v215
      REF: v216
      REF: v217
      REF: v218
      REF: v219
      REF: v246
      REF: v247
      REF: v248
      REF: v249
      REF: v250
      REF: v251
      REF: v271
      REF: v272
      REF: v273
      REF: v274
      REF: v275
      block0(): # succs:[1] preds:[]
        inst0: Op ops:[Def: v0i any] clobber:[]
        inst1: Op ops:[Def: v1i any] clobber:[]
        inst2: Op ops:[Def: v2i any] clobber:[]
        inst3: Op ops:[Def: v3i any] clobber:[]
        inst4: Op ops:[Def: v4i any] clobber:[]
        inst5: Op ops:[Def: v5i any] clobber:[]
        inst6: Op ops:[Def: v6i any] clobber:[]
        inst7: Op ops:[Def: v7i any] clobber:[]
        inst8: Branch ops:[] clobber:[]
      block1(): # succs:[2] preds:[0]
        inst9: Op ops:[Def: v8i any] clobber:[]
        inst10: Op ops:[Def: v9i any] clobber:[]
        inst11: Op ops:[Def: v10i any] clobber:[]
        inst12: Op ops:[Def: v11i any] clobber:[]
        inst13: Op ops:[Def: v12i any] clobber:[]
        inst14: Op ops:[Def: v13i any] clobber:[]
        inst15: Op ops:[Def: v14i any, Use: v11i reg, Use: v11i reg, Use: v11i reg] clobber:[]
        inst16: Op ops:[Def: v15i reg] clobber:[]
        inst17: Branch ops:[] clobber:[]
      block2(): # succs:[3] preds:[1, 20]
        inst18: Op ops:[Def: v16i reuse(1), Use: v15i reg, Use: v9i reg, Use: v9i reg] clobber:[]
        -- SAFEPOINT --
        inst19: Op ops:[Def: v17i reuse(2), Use: v16i reg, Use: v16i reg, Use: v16i reg] clobber:[]
        -- SAFEPOINT --
        inst20: Op ops:[Def: v18i reuse(2), Use: v17i reg, Use: v17i reg, Use: v17i reg] clobber:[]
        inst21: Op ops:[Def@Early: v19i reg, Use: v17i any, Use: v4i any, Use: v4i any] clobber:[]
        inst22: Op ops:[Def: v20i any] clobber:[]
        inst23: Branch ops:[] clobber:[]
      block3(): # succs:[4] preds:[2, 17]
        -- SAFEPOINT --
        inst24: Op ops:[Def: v21i reuse(1), Use: v19i reg] clobber:[]
        -- SAFEPOINT --
        inst25: Op ops:[Def@Early: v22i reg] clobber:[]
        -- SAFEPOINT --
        inst26: Op ops:[Def: v23i reuse(1), Use: v22i reg] clobber:[]
        -- SAFEPOINT --
        inst27: Op ops:[Def: v24i reuse(1), Use: v23i reg] clobber:[]
        -- SAFEPOINT --
        inst28: Op ops:[Def: v25i reuse(1), Use: v22i reg] clobber:[]
        -- SAFEPOINT --
        inst29: Op ops:[Def: v26i reuse(1), Use: v22i reg] clobber:[]
        inst30: Op ops:[Def: v27i reuse(2), Use: v5i reg, Use: v24i reg] clobber:[]
        inst31: Branch ops:[] clobber:[]
      block4(): # succs:[5] preds:[3, 23]
        -- SAFEPOINT --
        inst32: Op ops:[Def: v28i reuse(1), Use: v21i reg] clobber:[]
        -- SAFEPOINT --
        inst33: Op ops:[Def: v29i reuse(1), Use: v28i reg] clobber:[]
        -- SAFEPOINT --
        inst34: Op ops:[Def: v30i reuse(1), Use: v29i reg] clobber:[]
        -- SAFEPOINT --
        inst35: Op ops:[Def: v31i reuse(2), Use: v29i reg, Use: v29i reg, Use: v29i reg] clobber:[]
        -- SAFEPOINT --
        inst36: Op ops:[Def: v32i reuse(2), Use: v31i reg, Use: v31i reg, Use: v31i reg] clobber:[]
        -- SAFEPOINT --
        inst37: Op ops:[Def: v33i reuse(1), Use: v29i reg, Use: v32i reg, Use: v31i any] clobber:[]
        -- SAFEPOINT --
        inst38: Op ops:[Def: v34i reuse(1), Use: v31i reg] clobber:[]
        inst39: Branch ops:[] clobber:[]
      block5(): # succs:[6, 7] preds:[4]
        -- SAFEPOINT --
        inst40: Op ops:[Def: v35i reuse(1), Use: v28i reg] clobber:[]
        -- SAFEPOINT --
        inst41: Op ops:[Def: v36i reuse(1), Use: v35i reg] clobber:[]
        -- SAFEPOINT --
        inst42: Op ops:[Def: v37i reuse(1), Use: v36i reg] clobber:[]
        -- SAFEPOINT --
        inst43: Op ops:[Def: v38i reuse(1), Use: v37i reg] clobber:[]
        -- SAFEPOINT --
        inst44: Op ops:[Def: v39i reuse(1), Use: v36i reg] clobber:[]
        -- SAFEPOINT --
        inst45: Op ops:[Def: v40i reuse(1), Use: v36i reg] clobber:[]
        -- SAFEPOINT --
        inst46: Op ops:[Def: v41i reuse(1), Use: v40i reg] clobber:[]
        inst47: Branch ops:[Use: v28i reg] clobber:[]
      block6(v45): # succs:[31] preds:[5]
        -- SAFEPOINT --
        inst48: Op ops:[Def: v42i reuse(1), Use: v35i reg] clobber:[]
        -- SAFEPOINT --
        inst49: Op ops:[Def: v43i reuse(1), Use: v45i reg] clobber:[]
        inst50: Op ops:[Def: v44i reuse(3), Use: v45i any, Use: v45i reg, Use: v45i reg] clobber:[]
        inst51: Op ops:[Def@Early: v46i reg, Use: v45i any, Use: v44i any, Use: v44i any] clobber:[]
        -- SAFEPOINT --
        inst52: Op ops:[Def: v47i reuse(1), Use: v46i reg] clobber:[]
        -- SAFEPOINT --
        inst53: Op ops:[Def: v48i reuse(1), Use: v44i reg] clobber:[]
        inst54: Branch ops:[] clobber:[]
      block7(): # succs:[8] preds:[5]
        inst55: Op ops:[Def: v49i reuse(1), Use: v35i reg] clobber:[]
        inst56: Op ops:[Def: v50i reg] clobber:[]
        inst57: Op ops:[Def@Early: v51i reg] clobber:[]
        inst58: Op ops:[Def: v52i reuse(3), Use: v51i any, Use: v50i reg, Use: v51i reg] clobber:[]
        inst59: Op ops:[Def@Early: v53i reg, Use: v49i fixed(p0i)] clobber:[]
        inst60: Op ops:[Def: v54i reuse(1), Use: v51i reg] clobber:[]
        inst61: Op ops:[Def@Early: v55i reg, Use: v52i any] clobber:[]
        inst62: Op ops:[Def: v56i reuse(1), Use: v49i reg] clobber:[]
        inst63: Branch ops:[] clobber:[]
      block8(): # succs:[9] preds:[7, 29]
        inst64: Op ops:[Def: v57i reuse(1), Use: v35i reg] clobber:[]
        inst65: Op ops:[Def: v58i reuse(1), Use: v57i reg] clobber:[]
        inst66: Op ops:[Def: v59i reuse(1), Use: v58i reg] clobber:[]
        -- SAFEPOINT --
        inst67: Op ops:[Def: v60i reuse(1), Use: v59i reg] clobber:[]
        inst68: Op ops:[Def: v61i reuse(1), Use: v58i reg] clobber:[]
        inst69: Op ops:[Def@Early: v62i reg, Use: v58i reg] clobber:[]
        inst70: Op ops:[Def: v63i reuse(1), Use: v60i reg] clobber:[]
        inst71: Op ops:[Def: v64i reuse(3), Use: v57i reg, Use: v63i reg, Use: v57i reg] clobber:[]
        inst72: Op ops:[Def: v65i reuse(1), Use: v57i reg, Use: v63i reg] clobber:[]
        -- SAFEPOINT --
        inst73: Op ops:[Def: v66i any] clobber:[]
        inst74: Branch ops:[] clobber:[]
      block9(): # succs:[10] preds:[8, 32]
        -- SAFEPOINT --
        inst75: Op ops:[Def: v67i reuse(1), Use: v35i reg] clobber:[]
        -- SAFEPOINT --
        inst76: Op ops:[Def: v68i reuse(1), Use: v67i reg] clobber:[]
        -- SAFEPOINT --
        inst77: Op ops:[Def: v69i reuse(1), Use: v68i reg] clobber:[]
        -- SAFEPOINT --
        inst78: Op ops:[Def@Early: v70i reg] clobber:[]
        -- SAFEPOINT --
        inst79: Op ops:[Def: v71i reuse(1), Use: v68i reg] clobber:[]
        inst80: Branch ops:[] clobber:[]
      block10(): # succs:[11, 12] preds:[9]
        -- SAFEPOINT --
        inst81: Op ops:[Def: v72i reuse(1), Use: v70i reg] clobber:[]
        -- SAFEPOINT --
        inst82: Op ops:[Def: v73i reuse(1), Use: v72i reg] clobber:[]
        inst83: Op ops:[Def: v74i reuse(1), Use: v73i reg] clobber:[]
        -- SAFEPOINT --
        inst84: Op ops:[Def: v75i reuse(1), Use: v74i reg] clobber:[]
        -- SAFEPOINT --
        inst85: Op ops:[Def: v76i reuse(1), Use: v73i reg] clobber:[]
        inst86: Branch ops:[Use: v67i reg, Use: v68i reg, Use: v67i reg] clobber:[]
      block11(): # succs:[31] preds:[10]
        -- SAFEPOINT --
        inst87: Op ops:[Def: v77i reuse(1), Use: v73i reg] clobber:[]
        -- SAFEPOINT --
        inst88: Op ops:[Def: v78i reg] clobber:[]
        inst89: Op ops:[Def: v79i reuse(1), Use: v78i reg] clobber:[]
        inst90: Op ops:[Def@Early: v80i any, Use: v77i reg, Use: v77i reg, Use: v77i any] clobber:[]
        inst91: Op ops:[Def: v81i any] clobber:[]
        inst92: Branch ops:[] clobber:[]
      block12(v85, v86, v88): # succs:[13] preds:[10]
        inst93: Op ops:[Def: v82i any] clobber:[]
        inst94: Op ops:[Def: v83i any] clobber:[]
        inst95: Op ops:[Def: v84i any] clobber:[]
        inst96: Op ops:[Def: v87i any] clobber:[]
        inst97: Op ops:[Def: v89i any] clobber:[]
        inst98: Op ops:[Def: v90i any] clobber:[]
        inst99: Op ops:[Def: v91i any] clobber:[]
        inst100: Op ops:[Def: v92i any] clobber:[]
        inst101: Op ops:[Def: v93i any] clobber:[]
        inst102: Op ops:[Def: v94i reuse(1), Use: v82i reg, Use: v91i reg, Use: v87i any] clobber:[]
        inst103: Branch ops:[] clobber:[]
      block13(): # succs:[14, 15] preds:[12]
        inst104: Op ops:[Def: v95i reuse(1), Use: v90i reg] clobber:[]
        inst105: Op ops:[Def: v96i reg] clobber:[]
        inst106: Op ops:[Def: v97i any] clobber:[]
        inst107: Op ops:[Def: v98i any] clobber:[PReg(hw = 3, class = Int, index = 3), PReg(hw = 0, class = Int, index = 0)]
        inst108: Op ops:[Def@Early: v99i reg] clobber:[]
        inst109: Op ops:[Def: v100i any] clobber:[]
        inst110: Op ops:[Def: v101i any] clobber:[]
        inst111: Op ops:[Def: v102i any] clobber:[]
        inst112: Branch ops:[] clobber:[]
      block14(): # succs:[31] preds:[13]
        inst113: Op ops:[Def: v103i any] clobber:[]
        inst114: Op ops:[Def: v104i any] clobber:[]
        inst115: Op ops:[Def: v105i any] clobber:[]
        inst116: Op ops:[Def: v106i any] clobber:[]
        inst117: Op ops:[Def: v107i any] clobber:[]
        inst118: Op ops:[Def: v108i any] clobber:[]
        inst119: Op ops:[Def: v109i any] clobber:[]
        inst120: Op ops:[Def: v110i any] clobber:[]
        inst121: Branch ops:[] clobber:[]
      block15(): # succs:[16] preds:[13]
        inst122: Op ops:[Def: v111i reuse(1), Use: v102i reg, Use: v96i reg, Use: v101i any] clobber:[]
        inst123: Op ops:[Def: v112i reuse(1), Use: v111i reg] clobber:[]
        inst124: Op ops:[Def@Early: v113i reg, Use: v112i reg, Use: v0i any, Use: v0i any] clobber:[]
        inst125: Op ops:[Def: v114i any] clobber:[]
        inst126: Op ops:[Def: v115i any] clobber:[]
        inst127: Op ops:[Def: v116i reuse(1), Use: v114i reg] clobber:[]
        inst128: Op ops:[Def@Early: v117i reg, Use: v114i reg] clobber:[]
        inst129: Op ops:[Def: v118i any, Use: v2i any, Use: v2i any] clobber:[]
        inst130: Branch ops:[] clobber:[]
      block16(): # succs:[17, 18] preds:[15]
        inst131: Op ops:[Def: v119i reuse(2), Use: v2i any, Use: v70i reg] clobber:[]
        inst132: Op ops:[Def: v120i reuse(1), Use: v119i reg] clobber:[]
        inst133: Op ops:[Def: v121i reuse(1), Use: v120i reg] clobber:[]
        inst134: Op ops:[Def: v122i any] clobber:[]
        inst135: Op ops:[Def: v123i any] clobber:[]
        inst136: Op ops:[Def@Early: v124i any] clobber:[]
        inst137: Op ops:[Def: v125i any] clobber:[]
        inst138: Op ops:[Def: v126i any] clobber:[]
        inst139: Branch ops:[Use: v123i reg] clobber:[]
      block17(v127): # succs:[3] preds:[16]
        inst140: Op ops:[Def: v128i any] clobber:[]
        inst141: Op ops:[Def: v129i any] clobber:[]
        inst142: Op ops:[Def: v130i any] clobber:[]
        inst143: Op ops:[Def: v131i any] clobber:[PReg(hw = 0, class = Int, index = 0)]
        inst144: Op ops:[Def: v132i reuse(1), Use: v127i reg, Use: v127i reg, Use: v127i reg] clobber:[]
        inst145: Op ops:[Def: v133i reuse(1), Use: v130i reg, Use: v130i reg, Use: v130i reg] clobber:[]
        inst146: Op ops:[Def: v134i any] clobber:[]
        inst147: Op ops:[Def: v135i any] clobber:[]
        inst148: Op ops:[Def: v136i any] clobber:[]
        inst149: Op ops:[Def: v137i any] clobber:[]
        inst150: Op ops:[Def: v138i any] clobber:[]
        inst151: Op ops:[Def: v139i reuse(1), Use: v128i reg] clobber:[]
        inst152: Branch ops:[] clobber:[]
      block18(): # succs:[19] preds:[16]
        inst153: Op ops:[Def: v140i reuse(1), Use: v120i reg] clobber:[]
        inst154: Op ops:[Def: v141i reuse(1), Use: v140i reg] clobber:[]
        inst155: Op ops:[Def: v142i reuse(1), Use: v141i reg] clobber:[]
        inst156: Op ops:[Def: v143i reuse(1), Use: v142i reg] clobber:[]
        inst157: Op ops:[Def: v144i reuse(1), Use: v141i reg] clobber:[]
        inst158: Op ops:[Def@Early: v145i reg, Use: v141i reg] clobber:[]
        inst159: Op ops:[Def: v146i reuse(2), Use: v145i reg, Use: v143i reg] clobber:[]
        inst160: Op ops:[Def: v147i reuse(1), Use: v140i reg] clobber:[]
        inst161: Branch ops:[] clobber:[]
      block19(): # succs:[20, 21] preds:[18, 38, 41]
        -- SAFEPOINT --
        inst162: Op ops:[Def@Early: v148i reg] clobber:[]
        -- SAFEPOINT --
        inst163: Op ops:[Def: v149i reuse(1), Use: v148i reg] clobber:[]
        -- SAFEPOINT --
        inst164: Op ops:[Def: v150i reuse(2), Use: v149i reg, Use: v149i reg, Use: v149i reg] clobber:[]
        -- SAFEPOINT --
        inst165: Op ops:[Def: v151i reuse(2), Use: v149i reg, Use: v149i reg, Use: v149i reg] clobber:[]
        -- SAFEPOINT --
        inst166: Op ops:[Def: v152i reuse(3), Use: v11i any, Use: v151i reg, Use: v149i reg] clobber:[]
        inst167: Branch ops:[] clobber:[]
      block20(): # succs:[2] preds:[19]
        inst168: Op ops:[Def@Early: v153i reg] clobber:[]
        inst169: Op ops:[Def: v154i reuse(1), Use: v153i reg] clobber:[]
        inst170: Op ops:[Def: v155i reuse(1), Use: v154i reg] clobber:[]
        inst171: Op ops:[Def: v156i reuse(1), Use: v155i reg] clobber:[]
        inst172: Op ops:[Def: v157i reuse(1), Use: v154i reg] clobber:[]
        inst173: Op ops:[Def: v158i reuse(1), Use: v154i reg] clobber:[]
        inst174: Op ops:[Def: v159i reuse(1), Use: v156i reg] clobber:[]
        inst175: Op ops:[Def: v160i reuse(1), Use: v153i reg] clobber:[]
        inst176: Branch ops:[] clobber:[]
      block21(): # succs:[22] preds:[19]
        -- SAFEPOINT --
        inst177: Op ops:[Def: v161i reuse(1), Use: v149i reg] clobber:[]
        -- SAFEPOINT --
        inst178: Op ops:[Def: v162i reuse(1), Use: v152i reg] clobber:[]
        -- SAFEPOINT --
        inst179: Op ops:[Def: v163i reuse(1), Use: v35i reg] clobber:[]
        -- SAFEPOINT --
        inst180: Op ops:[Def: v164i reg, Use: v161i reg, Use: v163i any, Use: v163i reg] clobber:[]
        -- SAFEPOINT --
        inst181: Op ops:[Def: v165i reuse(3), Use: v20i reg, Use: v162i reg, Use: v151i reg] clobber:[]
        -- SAFEPOINT --
        inst182: Op ops:[Def: v166i reuse(1), Use: v164i reg] clobber:[]
        -- SAFEPOINT --
        inst183: Op ops:[Def@Early: v167i reg] clobber:[]
        -- SAFEPOINT --
        inst184: Op ops:[Def: v168i reuse(1), Use: v161i reg] clobber:[]
        -- SAFEPOINT --
        inst185: Op ops:[Def: v169i reuse(1), Use: v162i reg] clobber:[]
        inst186: Op ops:[Def: v170i reuse(1), Use: v161i reg] clobber:[]
        -- SAFEPOINT --
        inst187: Op ops:[Def@Early: v171i reg] clobber:[]
        inst188: Branch ops:[] clobber:[]
      block22(): # succs:[23, 24] preds:[21, 35]
        -- SAFEPOINT --
        inst189: Op ops:[Def: v172i reuse(1), Use: v35i reg] clobber:[]
        -- SAFEPOINT --
        inst190: Op ops:[Def: v173i reuse(1), Use: v172i reg] clobber:[]
        -- SAFEPOINT --
        inst191: Op ops:[Def: v174i reuse(1), Use: v173i reg] clobber:[]
        -- SAFEPOINT --
        inst192: Op ops:[Def: v175i reg, Use: v172i fixed(p0i)] clobber:[]
        -- SAFEPOINT --
        inst193: Op ops:[Def: v176i reuse(1), Use: v173i reg] clobber:[]
        inst194: Branch ops:[] clobber:[]
      block23(): # succs:[4] preds:[22]
        -- SAFEPOINT --
        inst195: Op ops:[Def: v177i reuse(1), Use: v176i reg] clobber:[]
        inst196: Op ops:[Def@Early: v178i reg, Use: v177i reg, Use: v177i any, Use: v177i any] clobber:[]
        inst197: Op ops:[Def: v179i reuse(1), Use: v177i reg, Use: v178i any] clobber:[]
        -- SAFEPOINT --
        inst198: Op ops:[Def@Early: v180i any, Use: v177i any, Use: v177i fixed(p0i)] clobber:[]
        -- SAFEPOINT --
        inst199: Op ops:[Def: v181i reuse(1), Use: v178i reg] clobber:[]
        inst200: Branch ops:[] clobber:[]
      block24(): # succs:[25] preds:[22]
        -- SAFEPOINT --
        inst201: Op ops:[Def: v182i reuse(1), Use: v172i reg] clobber:[]
        -- SAFEPOINT --
        inst202: Op ops:[Def: v183i reuse(1), Use: v182i reg] clobber:[]
        -- SAFEPOINT --
        inst203: Op ops:[Def: v184i reuse(1), Use: v183i reg] clobber:[]
        -- SAFEPOINT --
        inst204: Op ops:[Def: v185i reuse(1), Use: v184i reg] clobber:[]
        -- SAFEPOINT --
        inst205: Op ops:[Def: v186i reuse(1), Use: v183i reg] clobber:[]
        inst206: Branch ops:[Use: v172i reg] clobber:[]
      block25(v187): # succs:[26, 27] preds:[24]
        inst207: Op ops:[Def: v188i reuse(3), Use: v9i reg, Use: v187i reg, Use: v187i reg] clobber:[]
        inst208: Op ops:[Def: v189i reuse(1), Use: v188i reg] clobber:[]
        inst209: Op ops:[Def: v190i reuse(1), Use: v189i reg] clobber:[]
        inst210: Op ops:[Def: v191i reuse(1), Use: v188i reg] clobber:[]
        inst211: Branch ops:[] clobber:[]
      block26(): # succs:[40] preds:[25]
        inst212: Op ops:[Def: v192i reuse(1), Use: v188i reg] clobber:[]
        -- SAFEPOINT --
        inst213: Op ops:[Def: v193i reuse(1), Use: v192i reg, Use: v192i reg, Use: v192i reg] clobber:[]
        -- SAFEPOINT --
        inst214: Op ops:[Def: v194i reuse(2), Use: v193i reg, Use: v193i reg, Use: v193i reg] clobber:[]
        -- SAFEPOINT --
        inst215: Op ops:[Def: v195i reuse(1), Use: v192i reg, Use: v192i reg, Use: v192i reg] clobber:[]
        -- SAFEPOINT --
        inst216: Op ops:[Def@Early: v196i reg, Use: v195i fixed(p0i), Use: v195i reg, Use: v195i reg] clobber:[]
        -- SAFEPOINT --
        inst217: Op ops:[Def: v197i any] clobber:[PReg(hw = 0, class = Int, index = 0)]
        -- SAFEPOINT --
        inst218: Op ops:[Def: v198i reuse(1), Use: v195i reg] clobber:[]
        inst219: Branch ops:[] clobber:[]
      block27(): # succs:[28] preds:[25]
        inst220: Op ops:[Def: v199i reuse(1), Use: v187i reg] clobber:[]
        -- SAFEPOINT --
        inst221: Op ops:[Def: v200i reuse(1), Use: v199i reg] clobber:[]
        -- SAFEPOINT --
        inst222: Op ops:[Def: v201i reuse(1), Use: v200i reg] clobber:[]
        -- SAFEPOINT --
        inst223: Op ops:[Def: v202i reuse(1), Use: v201i reg] clobber:[]
        -- SAFEPOINT --
        inst224: Op ops:[Def: v203i reuse(1), Use: v200i reg] clobber:[]
        inst225: Branch ops:[] clobber:[]
      block28(): # succs:[29, 30] preds:[27]
        inst226: Op ops:[Def: v204i reuse(1), Use: v200i reg] clobber:[]
        -- SAFEPOINT --
        inst227: Op ops:[Def: v205i reuse(2), Use: v204i any, Use: v204i reg] clobber:[]
        -- SAFEPOINT --
        inst228: Op ops:[Def: v206i reuse(1), Use: v205i reg, Use: v205i reg, Use: v205i reg] clobber:[]
        -- SAFEPOINT --
        inst229: Op ops:[Def: v207i reuse(3), Use: v204i reg, Use: v204i reg, Use: v205i reg] clobber:[]
        inst230: Op ops:[Def@Early: v208i reg, Use: v205i reg, Use: v205i reg] clobber:[PReg(hw = 1, class = Int, index = 1), PReg(hw = 23, class = Int, index = 23)]
        inst231: Branch ops:[] clobber:[]
      block29(): # succs:[8] preds:[28]
        inst232: Op ops:[Def: v209i any] clobber:[]
        inst233: Op ops:[Def: v210i reuse(1), Use: v209i reg] clobber:[]
        inst234: Op ops:[Def: v211i reuse(1), Use: v210i reg] clobber:[]
        inst235: Op ops:[Def: v212i reg] clobber:[]
        inst236: Op ops:[Def: v213i reuse(1), Use: v210i reg] clobber:[]
        inst237: Branch ops:[] clobber:[]
      block30(): # succs:[31] preds:[28]
        inst238: Op ops:[Def: v214i reuse(1), Use: v29i reg, Use: v189i reg, Use: v204i reg] clobber:[]
        inst239: Op ops:[Def: v215i reuse(1), Use: v214i reg] clobber:[]
        inst240: Op ops:[Def@Early: v216i reg, Use: v215i reg] clobber:[]
        inst241: Op ops:[Def: v217i any, Use: v215i any, Use: v0i any] clobber:[]
        inst242: Op ops:[Def: v218i reuse(1), Use: v215i reg] clobber:[]
        inst243: Op ops:[Def@Early: v219i reg, Use: v0i any] clobber:[]
        inst244: Op ops:[Def: v220i any] clobber:[]
        inst245: Branch ops:[] clobber:[]
      block31(): # succs:[32, 33] preds:[6, 11, 14, 30]
        inst246: Op ops:[Def: v221i any] clobber:[]
        inst247: Op ops:[Def: v222i any] clobber:[]
        inst248: Op ops:[Def: v223i reuse(1), Use: v222i reg] clobber:[]
        -- SAFEPOINT --
        inst249: Op ops:[Def: v224i reuse(1), Use: v221i reg] clobber:[]
        inst250: Op ops:[Def@Early: v225i reg] clobber:[]
        inst251: Branch ops:[] clobber:[]
      block32(): # succs:[9] preds:[31]
        inst252: Op ops:[Def: v226i any] clobber:[]
        -- SAFEPOINT --
        inst253: Op ops:[Def: v227i any] clobber:[]
        inst254: Op ops:[Def: v228i reg] clobber:[]
        inst255: Op ops:[Def: v229i any] clobber:[]
        inst256: Op ops:[Def: v230i any] clobber:[]
        inst257: Branch ops:[] clobber:[]
      block33(): # succs:[34] preds:[31]
        inst258: Op ops:[Def: v231i any] clobber:[]
        inst259: Op ops:[Def: v232i any] clobber:[]
        inst260: Op ops:[Def: v233i any] clobber:[]
        inst261: Op ops:[Def: v234i any] clobber:[]
        inst262: Op ops:[Def: v235i any] clobber:[]
        inst263: Branch ops:[] clobber:[]
      block34(): # succs:[35, 36] preds:[33]
        inst264: Op ops:[Def: v236i any] clobber:[]
        inst265: Op ops:[Def: v237i any] clobber:[]
        inst266: Op ops:[Def: v238i any] clobber:[]
        -- SAFEPOINT --
        inst267: Op ops:[Def: v239i reuse(1), Use: v237i reg] clobber:[]
        -- SAFEPOINT --
        inst268: Op ops:[Def: v240i reuse(1), Use: v237i reg] clobber:[]
        inst269: Branch ops:[Use: v235i reg] clobber:[]
      block35(): # succs:[22] preds:[34]
        inst270: Op ops:[Def: v241i any] clobber:[]
        inst271: Op ops:[Def: v242i any] clobber:[]
        inst272: Op ops:[Def: v243i any] clobber:[]
        inst273: Op ops:[Def: v244i any] clobber:[]
        inst274: Op ops:[Def: v245i any] clobber:[]
        inst275: Branch ops:[] clobber:[]
      block36(v246): # succs:[37] preds:[34]
        inst276: Op ops:[Def: v247i reuse(1), Use: v246i reg] clobber:[]
        inst277: Op ops:[Def@Early: v248i reg] clobber:[]
        inst278: Op ops:[Def: v249i any] clobber:[]
        inst279: Op ops:[Def: v250i any] clobber:[]
        inst280: Op ops:[Def: v251i any] clobber:[]
        inst281: Branch ops:[] clobber:[]
      block37(): # succs:[38, 39] preds:[36]
        inst282: Op ops:[Def: v252i any] clobber:[]
        inst283: Op ops:[Def: v253i any] clobber:[]
        inst284: Op ops:[Def: v254i any] clobber:[]
        inst285: Op ops:[Def: v255i any] clobber:[]
        inst286: Op ops:[Def: v256i any] clobber:[]
        inst287: Op ops:[Def: v257i any] clobber:[]
        inst288: Op ops:[Def: v258i any] clobber:[]
        inst289: Op ops:[Def: v259i any] clobber:[]
        inst290: Op ops:[Def: v260i any] clobber:[]
        inst291: Branch ops:[] clobber:[]
      block38(): # succs:[19] preds:[37]
        inst292: Op ops:[Def: v261i any] clobber:[]
        inst293: Op ops:[Def: v262i any] clobber:[]
        inst294: Op ops:[Def: v263i any] clobber:[]
        inst295: Op ops:[Def: v264i any] clobber:[]
        inst296: Op ops:[Def: v265i any] clobber:[]
        inst297: Branch ops:[] clobber:[]
      block39(): # succs:[40] preds:[37]
        inst298: Op ops:[Def: v266i any] clobber:[]
        inst299: Op ops:[Def: v267i any] clobber:[]
        -- SAFEPOINT --
        inst300: Op ops:[Def: v268i any] clobber:[]
        -- SAFEPOINT --
        inst301: Op ops:[Def: v269i reuse(1), Use: v267i reg] clobber:[]
        inst302: Op ops:[Def@Early: v270i reg, Use: v267i reg] clobber:[]
        inst303: Branch ops:[] clobber:[]
      block40(): # succs:[41, 42] preds:[26, 39]
        inst304: Op ops:[Def: v271i any] clobber:[]
        inst305: Op ops:[Def: v272i any] clobber:[]
        inst306: Op ops:[Def: v273i any] clobber:[]
        inst307: Op ops:[Def: v274i any] clobber:[]
        inst308: Op ops:[Def: v275i any] clobber:[]
        inst309: Op ops:[Def: v276i any] clobber:[]
        inst310: Op ops:[Def: v277i any] clobber:[]
        inst311: Op ops:[Def: v278i any] clobber:[]
        inst312: Branch ops:[] clobber:[]
      block41(): # succs:[19] preds:[40]
        inst313: Op ops:[Def: v279i any] clobber:[]
        inst314: Op ops:[Def: v280i any] clobber:[]
        inst315: Op ops:[Def: v281i any] clobber:[]
        inst316: Op ops:[Def: v282i any] clobber:[]
        inst317: Op ops:[Def: v283i any] clobber:[]
        inst318: Branch ops:[] clobber:[]
      block42(): # succs:[43] preds:[40]
        inst319: Op ops:[Def: v284i any] clobber:[]
        inst320: Op ops:[Def: v285i any] clobber:[]
        inst321: Op ops:[Def: v286i any] clobber:[]
        inst322: Op ops:[Def: v287i any] clobber:[]
        inst323: Op ops:[Def: v288i any] clobber:[]
        inst324: Branch ops:[] clobber:[]
      block43(): # succs:[44] preds:[42]
        inst325: Op ops:[Def: v289i any] clobber:[]
        inst326: Op ops:[Def: v290i any] clobber:[]
        inst327: Op ops:[Def: v291i any] clobber:[]
        inst328: Op ops:[Def: v292i any] clobber:[]
        inst329: Op ops:[Def: v293i any] clobber:[]
        inst330: Branch ops:[] clobber:[]
      block44(): # succs:[] preds:[43]
        inst331: Op ops:[Def: v294i any] clobber:[]
        inst332: Op ops:[Def: v295i any] clobber:[]
        inst333: Op ops:[Def: v296i any] clobber:[]
        inst334: Op ops:[Def: v297i any] clobber:[]
        inst335: Op ops:[Def: v298i any] clobber:[]
        inst336: Op ops:[Def: v299i any] clobber:[]
        inst337: Op ops:[Def: v300i any] clobber:[]
        -- SAFEPOINT --
        inst338: Op ops:[Def: v301i any] clobber:[]
        inst339: Op ops:[Def@Early: v302i reg] clobber:[]
        -- SAFEPOINT --
        inst340: Op ops:[Def: v303i reuse(1), Use: v302i reg] clobber:[]
        -- SAFEPOINT --
        inst341: Op ops:[Def: v304i reuse(1), Use: v301i reg] clobber:[]
        inst342: Ret ops:[] clobber:[]
    }
    ,
}
```

### PR DESCRIPTION
**Pull request by cfallin**
Changes in computation of bundle priorities during review of the initial
PR introduced a possible mis-ordering of priorities: inner-loop bundle
use weights could exceed the weights of 1_000_000 and 2_000_000 used for
minimal bundles without and with fixed uses (respectively). These two
kinds of minimal bundle are meant to be the highest-priority bundles,
evicting any other bundle they need to, because they can't be split
further. This PR introduces two special bundle weights for these two
kinds of bundles, and clamps all other bundle weights to just below
them.

Thanks to @Amanieu for reporting the issue! Fixes #19.

### CODE REVIEW

File: src/ion/data_structures.rs [hunk 1]
```diff
@@ -185,6 +185,11 @@ pub struct LiveBundle {
     pub spill_weight_and_props: u32,
 }
 
+pub const BUNDLE_MAX_SPILL_WEIGHT: u32 = (1 << 29) - 1;
+pub const MINIMAL_FIXED_BUNDLE_SPILL_WEIGHT: u32 = BUNDLE_MAX_SPILL_WEIGHT;
+pub const MINIMAL_BUNDLE_SPILL_WEIGHT: u32 = BUNDLE_MAX_SPILL_WEIGHT - 1;
+pub const MINIMAL_BUNDLE_MAX_NORMAL_SPILL_WEIGHT: u32 = BUNDLE_MAX_SPILL_WEIGHT - 2;
```
Comment (Amanieu) [inline src/ion/data_structures.rs:191]:
```suggestion
pub const MAX_NORMAL_SPILL_WEIGHT: u32 = BUNDLE_MAX_SPILL_WEIGHT - 2;
```
If I understand correctly this is the maximum spill weight for non-minimal bundles.

Comment (cfallin) [reply src/ion/data_structures.rs]: Indeed, poorly named, sorry! Fixed.

**Review by Amanieu — APPROVED** [review]

**Review by pchickey — APPROVED** [review]
